name: SONiC Test Cases Issue Report
description: File a bug report, test gap, enhancement or regression for a test case.
title: " "
labels: []
projects: ["sonic-mgmt"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

        If you are reporting a new issue, make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.
        
        If you suspect your issue is a bug, please edit your issue description to include the BUG REPORT INFORMATION shown below. If you fail to provide this information within 7 days, we cannot debug your issue and will close it. We will however, reopen it if you later provide the information.
        
        For more information about reporting issues, see [SONiC Issue Reporting Page](https://github.com/sonic-net/SONiC/wiki#report-issues)

  - type: markdown
    id: tc-contact-links
    attributes:
      value: |
        Please ask and answer questions here at the [SONiC Support Forums](https://groups.google.com/forum/#!forum/sonicproject)

  - type: checkboxes
    id: tc-issue-type
    attributes:
      label: Issue Type
      options:
        - label: Bug
        - label: Test Gap
        - label: Enhancement
        - label: Regression
    validations:
      required: true

  - type: dropdown
    id: tc-platform
    attributes:
      label: Is it platform specific
      description: Platform name
      options:
        - generic      
        - barefoot
        - broadcom
        - cavium
        - centec
        - innovium
        - marvell
        - mellanox
        - nephos
      default: 0
    validations:
      required: true

  - type: dropdown
    id: tc-severity
    attributes:
      label: Importance or Severity
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: tc-regression-previous-working-version
    attributes:
      label: Previous Working Version (only for Regression)
      description: Specify the last known version where the functionality worked as expected
      placeholder: e.g., 202311 or Git SHA
    validations:
      required: true

  - type: textarea
    id: tc-description
    attributes:
      label: Description of the bug, test gap, enhancement or regression
      description: Description of the bug, test gap, enhancement or regression
      placeholder: Description of the bug, test gap, enhancement or regression
    validations:
      required: true

  - type: markdown
    id: tc-note-1
    attributes:
      value: |
        ## Field information:
          - For a **Bug Report** provide **Steps to Reproduce** the issue
          - For a **Test Gap** provide **Affected Area**
          - For an **Enhancement** provide **Current Behavior**
          - For a **Regression** provide **Steps to Reproduce**

  - type: textarea
    id: tc-str-aa-cb
    attributes:
      label: Steps to Reproduce
      description: Steps to Reproduce
    validations:
      required: true

  - type: markdown
    id: tc-note-2
    attributes:
      value: |
        ## Field information:
          - For a **Bug Report** provide the **Actual and expected behavior**
          - For a **Test Gap** provide **Impact of missing tests and proposed tests**
          - For an **Enhancement** provide **Proposed Behavior and use case**
          - For a **Regression** provide **Impact of Regression**

  - type: textarea
    id: tc-ab-impact-pb
    attributes:
      label: Actual Behavior and Expected Behavior or Impact or Proposed Behavior
      description: Actual Behavior and Expected Behavior or Impact or Proposed Behavior
    validations:
      required: true

  - type: textarea
    id: tc-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tc-output
    attributes:
      label: Output of `show version`
      description: Please copy and paste output of `show version`. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    id: tc-attach-logs
    attributes:
      value: |
        Attach debug file (if any) from: `sudo generate_dump` or other logs.
  - type: textarea
    id: tc-bug-attachments
    attributes:
      label: Attach files (if any)
