name: SONiC Test Cases Issue Report
description: File a bug report, test gap, enhancement or regression for a test case.
title: "[Bug|Test Gap|Enhancement|Regression] "
labels: []
projects: ["sonic-mgmt"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

        If you are reporting a new issue, make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.
        
        If you suspect your issue is a bug, please edit your issue description to include the BUG REPORT INFORMATION shown below. If you fail to provide this information within 7 days, we cannot debug your issue and will close it. We will however, reopen it if you later provide the information.
        
        For more information about reporting issues, see [SONiC Issue Reporting Page](https://github.com/sonic-net/SONiC/wiki#report-issues)

  - type: markdown
    id: tc-contact-links
    attributes:
      value: |
        Please ask and answer questions here at the [SONiC Support Forums](https://groups.google.com/forum/#!forum/sonicproject)

  - type: checkboxes
    id: tc-issue-type
    attributes:
      label: Issue Type
      options:
        - Bug Report
        - Test Gap
        - Enhancement
        - Regression
    validations:
      required: true

  - type: dropdown
    id: tc-platform
    attributes:
      label: Is it platform specific
      description: Platform name
      options:
        - generic      
        - barefoot
        - broadcom
        - cavium
        - centec
        - innovium
        - marvell
        - mellanox
        - nephos
      default: 0
    validations:
      required: true

  - type: dropdown
    id: tc-severity
    attributes:
      label: Importance or Severity
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

---

  <details>
  <summary>Click here to expand Bug Report Instructions and Fields</summary>
  - type: textarea
    id: tc-bug-description
    attributes:
      label: Bug Description
      description: Description of the bug
      placeholder: Description of the bug
    validations:
      required: true

  - type: textarea
    id: tc-bug-steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: tc-bug-actual-behavior
    attributes:
      label: Actual Behavior and Expected Behavior
      description: Actual Behavior and Expected Behavoior
    validations:
      required: true

  - type: textarea
    id: tc-bug-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tc-bug-output
    attributes:
      label: Output of `show version`
      description: Please copy and paste output of `show version`. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    id: tc-bug-attach-logs
    attributes:
      value: |
        Attach debug file (if any) from: `sudo generate_dump` or other logs.
  - type: textarea
    id: tc-bug-attachments
    attributes:
      label: Attach files (if any)
  </details>

---

  <details>
  <summary>Click here to expand Test Gap Instructions and Fields</summary>
  - type: textarea
    id: tc-tg-description
    attributes:
      label: Test Gap Description
      description: Description of the test gap
      placeholder: Description of the test gap
    validations:
      required: true

  - type: textarea
    id: tc-tg-affected-area
    attributes:
      label: Affected Area
      description: Affected Area
    validations:
      required: true

  - type: textarea
    id: tc-tg-impact-proposed-tests
    attributes:
      label: Impact of missing tests and proposed tests
      description: Impact of missing tests and proposed tests
    validations:
      required: true

  - type: textarea
    id: tc-tg-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tc-tg-output
    attributes:
      label: Output of `show version`
      description: Please copy and paste output of `show version`. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    id: tc-tg-attach-logs
    attributes:
      value: |
        Attach debug file (if any) from: `sudo generate_dump` or other logs.
  - type: textarea
    id: tc-tg-attachments
    attributes:
      label: Attach files (if any)
  </details>

---

  <details>
  <summary>Click here to expand Enhancement Instructions and Fields</summary>
  - type: textarea
    id: tc-enhacement-description
    attributes:
      label: Description of the enhancement
      description: Description of the enhancement
      placeholder: Description of the enhancement
    validations:
      required: true

  - type: textarea
    id: tc-enhancement-current-behavior
    attributes:
      label: Current Behavior
      description: Current Behavior
    validations:
      required: true

  - type: textarea
    id: tc-enhancement-proposed-behavior
    attributes:
      label: Proposed Behavior
      description: Proposed Behavior
    validations:
      required: true

  - type: textarea
    id: tc-enhancement-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tc-enhancement-output
    attributes:
      label: Output of `show version`
      description: Please copy and paste output of `show version`. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    id: tc-enhancement-attach-logs
    attributes:
      value: |
        Attach debug file (if any) from: `sudo generate_dump` or other logs.
  - type: textarea
    id: tc-enhancement-attachments
    attributes:
      label: Attach files (if any)
  </details>

---

  <details>
  <summary>Click here to expand Regression Instructions and Fields</summary>
  - type: input
    id: tc-regression-previous-working-version
    attributes:
      label: Previous Working Version
      description: Specify the last known version where the functionality worked as expected
      placeholder: e.g., 202311 or Git SHA
    validations:
      required: true

  - type: textarea
    id: tc-regression-steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: tc-regression-impact
    attributes:
      label: Impact of Regression
      description: Impact of Regression
      placeholder: e.g., Affects the following area or functionality, impacts performance, etc.
    validations:
      required: true

  - type: textarea
    id: tc-regression-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tc-regression-output
    attributes:
      label: Output of `show version`
      description: Please copy and paste output of `show version`. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    id: tc-regression-attach-logs
    attributes:
      value: |
        Attach debug file (if any) from: `sudo generate_dump` or other logs.
  - type: textarea
    id: tc-regression-attachments
    attributes:
      label: Attach files (if any)
  </details>
