name: Process the Issue Report
on:
  issues:
    types: [opened]
jobs:
  apply-type-label:
    runs-on: ubuntu-latest
    steps:
        uses: actions/github-script@v7
        with:
          script: |
            const issueType = context.payload.issue.body.match(/Issue Type:\s*(.*)/)[1];
            const labels = {
              'Test Gap': 'test-gap',
              'Bug Report': 'bug',
              'Enhancement': 'enhancement'
            };
            if issueType in labels {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                labels: [labels[issueType]]
              });
            }
