name: Process the Issue Report
on:
  issues:
    types: [opened]
jobs:
  apply-type-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issueType = context.payload.issue.body.match(/Issue Type\s*(.*)/)[1];
            console.log('Issue Type:', issueType);
            if (issueType === 'Test Gap') {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                labels: ['test-gap']
              });
            }
            if (issueType === 'Bug Report') {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                labels: ['bug']
              });
            }
            if (issueType === 'Enhancement') {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                labels: ['enhancement']
              });
            }